import { defaultTheme } from "../../themes/default/index.js";
import type { BreadcrumbItemData } from "../../themes/types.js";
import type { PageData, SidebarItem, TocItem } from "../../types.js";
import type { ParentComponent } from "solid-js";

// @ts-ignore: generated by the docs plugin from the configured theme path.
import { theme as configuredTheme } from "virtual:nikala-docs-theme";

interface DocsLayoutShellProps {
  config: any;
  tree: SidebarItem[];
  currentPage: PageData | undefined;
  breadcrumbs: BreadcrumbItemData[];
  toc: TocItem[];
  prev: { title: string; href: string } | undefined;
  next: { title: string; href: string } | undefined;
}

export const DocsLayoutShell: ParentComponent<DocsLayoutShellProps> = (props) => {
  const ThemeProvider = configuredTheme.Provider || defaultTheme.Provider;
  if (!ThemeProvider) throw new Error("Nikala Docs theme must provide a ThemeProvider");
  return (
    <ThemeProvider defaultTheme="system" storageKey="nikala-theme">
      <configuredTheme.Layout config={props.config} tree={props.tree} currentPage={props.currentPage} breadcrumbs={props.breadcrumbs} toc={props.toc} prev={props.prev} next={props.next}>
        {props.children}
      </configuredTheme.Layout>
    </ThemeProvider>
  );
};
